# Generated by Django 4.2.17 on 2025-02-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
