# Generated by Django 4.2.17 on 2025-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carts',
            field=models.ManyToManyField(blank=True, null=True, to='Home.cart'),
        ),
    ]
