# Generated by Django 4.2.17 on 2025-02-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_products_rating_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.ManyToManyField(blank=True, to='Home.rating'),
        ),
    ]
