# Generated by Django 4.2.17 on 2025-02-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_products_orders_alter_profile_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carts',
            field=models.ManyToManyField(blank=True, to='Home.cart'),
        ),
    ]
