# Generated by Django 4.2.17 on 2025-02-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rating_products_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='freshness_duration',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rebly',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
