# Generated by Django 4.2.17 on 2025-02-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_products_color_alter_cart_number_alter_profile_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue')], max_length=25),
        ),
    ]
