# Generated by Django 4.2.17 on 2025-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='breif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='freshness_duration',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='quality_checking',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
