# Generated by Django 4.2.17 on 2025-02-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_products_breif_products_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='box_contains',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='packeting',
            field=models.CharField(blank=True, choices=[('Without touch of hand', 'Without touch of hand'), ('With touch of hand', 'With touch of hand')], max_length=50, null=True),
        ),
    ]
