# Generated by Django 4.2.17 on 2025-02-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_products_box_contains_products_packeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.TextField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.profile')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.rebly')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='Home.comments'),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, to='Home.rating'),
        ),
    ]
