# Generated by Django 4.2.17 on 2025-02-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_comments_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebly',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
