# Generated by Django 4.2.17 on 2025-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_rebly_rating_comments_products_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='box_contains',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='breif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='comment',
            field=models.ManyToManyField(blank=True, to='Home.comments'),
        ),
        migrations.AlterField(
            model_name='products',
            name='depth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='packeting',
            field=models.CharField(choices=[('Without touch of hand', 'Without touch of hand'), ('With touch of hand', 'With touch of hand')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='quality_checking',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.ManyToManyField(blank=True, to='Home.rating'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='width',
            field=models.IntegerField(),
        ),
    ]
