# Generated by Django 4.2.17 on 2025-02-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_products_box_contains_alter_products_breif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TimeField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='breif',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
